### ISSUE TITLE
这是我在使用插件时遇到的一些问题，我在测试后整理现在反馈给您。

### ISSUE THREAD

**Issue by 1642579950** [tanyaofei/minecraft-fakeplayer#10]
在 BC 环境中 （waterfall-1.20-536.jar） paper 1.20.1 子服中测试

1.假人死亡后，无法再召唤出同名的假人 （ 召唤时会直接显示死亡 ） 视频链接 http://www.ahmy.cc/未命名项目.mov
2.在 BC 服中，不同子服可以召唤出同一个ID的假人 ！！！！这样有跨服背包同步的就可以刷物品
3.在 BC 服中，无法限制玩家可创建假人的数量 （ 每个子服独享player-limit: 1 这个值 ）
4.假人无法攻击盔甲架 ( 刷怪塔需要攻击盔甲架来最大化发挥横扫属性 )
5.当假人 [ 看向指定位置 选择实体时 ] 假人也会看向掉落物等实体 （ 如果可以希望增加指定实体 ）
6.假人周围的水不会结冰 （ 假人不会触发水结冰 ）

**Comment by tanyaofei** [comment]
1.18 修复了 1、5 bug，剩余的bug不是由 `fakeplayer` 引起的。
