### ISSUE TITLE
希望可以新增是否自动清理假人的配置

### ISSUE THREAD

**Issue by Alexios-cd** [tanyaofei/minecraft-fakeplayer#100]
看到服务器日志和相关的代码了解到，在创建者下线时，默认经过两个周期（每周期6000毫秒）,尊贵的假人插件会自动清理创建者创建的假人，考虑到使用假人是为了保持区块加载，希望伟大的作者可以加入是否自动清理假人的配置。
或者考虑扩展可以加入以下配置：
1. 每个玩家可以创建假人的最大数量。
2. 是否自动清理假人
3. 自动清理假人的周期（假人最多保留多长时间）

因为目前个人自己建了服务器，只是自己玩，所以有这个自己下线后，长期关机的需求，希望伟大的作者可以考虑。

**Comment by Alexios-cd** [comment]
对不起，我眼瞎。没有看到配置

**Comment by tanyaofei** [comment]
食用愉快～
