### ISSUE TITLE
假人受伤（受到击退？）之后会消失

### ISSUE THREAD

**Issue by czauw** [tanyaofei/minecraft-fakeplayer#101]
**Describe the bug / 描述你的 bug 情况**
假人受到伤害之后直接消失了，使用tp指令也无法把它tp回来，如果tp到他的位置发现自己卡在主世界的边界，但它并没有退出服务器。

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
假人受到任何带有击退的伤害（来自玩家或者怪物，被火烧或者岩浆貌似不会）都会触发这个状况。
**Server information / 服务器信息**
 - Software / 核心: paper 1.20.1
 - Java: 21
 > This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

**Additional context / 更多信息**
![image](https://github.com/user-attachments/assets/dd21d949-da1b-4691-be1c-a62acf2a7ca8)

安装的插件如上

**Comment by tanyaofei** [comment]
[0.3.11](https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.11) 已解决
