### ISSUE TITLE
Problem not FP Auto Spawn When server is started / 简要的标题有利于检索

### ISSUE THREAD

**Issue by Jackmarksons** [tanyaofei/minecraft-fakeplayer#102]
**Describe the bug / 描述你的 bug 情况**
A clear and concise description of what the bug is. / 简单描述这是一个什么 bug

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. ... The problem is when i restart the server and wait it dosent spawn the fakeplayers and i have set it on prevent-kicking ALWAYS and alot more.
2. ... can i have your discord so it will be great if we fix issue and i show you everything.
3. ... my discord is: Yetr
4. ...

**Server information / 服务器信息**
 - Software / 核心: [e.g. Purpur 1.20.1]
 - Java: [e.g. 21]
 - Version / 版本 [e.g. 0.3.1]

**Additional context / 更多信息**
Add any other context about the problem here. Such as log and plugin list / 添加更多有帮助的信息，如插件列表、日志

**Comment by Jackmarksons** [comment]
give me your discord username please or discord server.

**Comment by tanyaofei** [comment]
well，fakeplayer will not auto respawn after you restarted the server
