### ISSUE TITLE
1.21.1 paper端服务器如何添加此插件

### ISSUE THREAD

**Issue by EXCALIBURYaoGod** [tanyaofei/minecraft-fakeplayer#103]
**Describe the bug / 描述你的 bug 情况**
A clear and concise description of what the bug is. / 简单描述这是一个什么 bug

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. ...
2. ...
3. ...
4. ...

**Server information / 服务器信息**
 - Software / 核心: [e.g. Purpur 1.20.1]
 - Java: [e.g. 21]
 - Version / 版本 [e.g. 0.3.1]

**Additional context / 更多信息**
Add any other context about the problem here. Such as log and plugin list / 添加更多有帮助的信息，如插件列表、日志

**Comment by tanyaofei** [comment]
我觉得你应该是去补充“服务端如何安装插件”的知识，FakePlayer 与其他插件安装方式没有区别
