### ISSUE TITLE
paper1.20.4第一次生成假玩家之后立马掉线

### ISSUE THREAD

**Issue by xinge4088** [tanyaofei/minecraft-fakeplayer#105]
**Describe the bug / 描述你的 bug 情况**
A clear and concise description of what the bug is. / 简单描述这是一个什么 bug
第一次生成假玩家之后立马掉线
**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
第一次召唤玩家/fp spawn
立马提示[13:59:58 INFO]: mosi54088_1 lost connection: PacketEvents 2.0 failed to inject
召唤第二次就正常了
**Server information / 服务器信息**
 - Software / 核心: paper1.20.4
 - Java: 21
 - Version / 版本 0.3.12

**Additional context / 更多信息**
Add any other context about the problem here. Such as log and plugin list / 添加更多有帮助的信息，如插件列表、日志
[13:59:58 INFO]: mosi54088_1 lost connection: PacketEvents 2.0 failed to inject

**Comment by tanyaofei** [comment]
看首页的 FAQ，里面有说明
