### ISSUE TITLE
[Question] Sleeping percentage

### ISSUE THREAD

**Issue by sirlupusdev** [tanyaofei/minecraft-fakeplayer#106]
Hello, 
a (more or less) simple question: Do fake players count towards the sleepingPercentage gamerule or are they exempt from that (e. g. the PlayerDoll plugin makes the gamerule ignore fake players)?
Thanks for your help in advance!

**Comment by tanyaofei** [comment]
https://github.com/tanyaofei/minecraft-fakeplayer/blob/b472fe2938622339e83d5091f1fd241ba8185a09/fakeplayer-core/src/main/java/io/github/hello09x/fakeplayer/core/entity/Fakeplayer.java#L109

Yes, they are exempted
