### ISSUE TITLE
假人生成时满饱食度

### ISSUE THREAD

**Issue by NormanLord** [tanyaofei/minecraft-fakeplayer#107]
**Describe the feature you'd like / 描述你想要的新特性**
...假人生成时设置为满的饱食度。假人挂完机器后，就会一直饥饿（通过信标回血），然后在别的地方挂这个假人就会饿死，现在是给他使用use指令吃东西Q^Q

**Comment by tanyaofei** [comment]
这个可以有

**Comment by tanyaofei** [comment]
https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.13
