### ISSUE TITLE
Paper 1.21.4 Support

### ISSUE THREAD

**Issue by tofo2** [tanyaofei/minecraft-fakeplayer#108]
**Describe the feature you'd like / 描述你想要的新特性**
...

I'd like Support for Minecraft 1.21.4. Because it fails to start with the 1.21.3 version

**Comment by tanyaofei** [comment]
Could u plz send me the logs so I can check what the issue is?👋

**Comment by tanyaofei** [comment]
https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.13

**Comment by tofo2** [comment]
Thank you.
