### ISSUE TITLE
First Fakeplayer that spawns is invisible - Paper 1.21.3

### ISSUE THREAD

**Issue by jvliaaaaan** [tanyaofei/minecraft-fakeplayer#109]
**Describe the bug / 描述你的 bug 情况**
A clear and concise description of what the bug is. / 简单描述这是一个什么 bug
When spawning in the first Fakeplayer with "/fp spawn", it is invisible.
Every Fakeplayer after that works fine.
The "invisible" Fake Player is not visible to any Player. It does not show in Tab list. It does not show up when you enter a command that shows Player names.
It does show up, if you hover over the online players from the Server Selection screen (The default Minecraft one) and it can still be teleported, kicked etc with commands. They just dont auto complete.
As I said, it's only the first player and the others still work.
Worked previously on my old Server which was on 1.21
This one is now on 1.21.3
Console does not show any errors.

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. Install the plugin
2. Start the Server
3. Spawn a fake player with "/fp spawn"
4. (Don't) see the result

**Server information / 服务器信息**
 - Software / 核心: Paper 1.21.3 Build #81 
 - Java: Java 22
 - Version / 版本 0.3.12

**Additional context / 更多信息**
Add any other context about the problem here. Such as log and plugin list / 添加更多有帮助的信息，如插件列表、日志
The only plugins on my Server when testing this are the fakeplayer and CommandAPI.
Console does not show any errors. Same as when spawning any other Player after that.

**Comment by jvliaaaaan** [comment]
(I did not want to link to the Build of this Plugin, but the PaperMC build version)

**Comment by jvliaaaaan** [comment]
Seems to be a problem with another Plugin that I'm working with. I deleted it for testing and the Issue was still there even after restarting the Server. It has issues when "setVisibleByDefault(false);" is used. My bad, apologies!

**Comment by tanyaofei** [comment]
> Seems to be a problem with another Plugin that I'm working with. I deleted it for testing and the Issue was still there even after restarting the Server. It has issues when "setVisibleByDefault(false);" is used. My bad, apologies!

it's okay
