### ISSUE TITLE
/fakeplayer skin dosent work

### ISSUE THREAD

**Issue by AMERICANNEWSGMS** [tanyaofei/minecraft-fakeplayer#111]
**Describe the bug / 描述你的 bug 情况**
The /fakeplayer skin dosent work

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. /fakeplayer skin <name
2. see if it works

**Server information / 服务器信息**
 - Software /  paper 1.21.3
 - Java: newest
 - Version / 1.21.3

**Additional context / 更多信息**
no

**Comment by tanyaofei** [comment]
`/fp skin` is an asynchronously command, so there may not be any error messages. This could be due to network issues or mojang api rate limit if you are copying a player whom is not online

**Comment by AMERICANNEWSGMS** [comment]
ok thanks
