### ISSUE TITLE
[bug]0.18版本，设置玩家最大假人数不生效

### ISSUE THREAD

**Issue by shawnlihst** [tanyaofei/minecraft-fakeplayer#14]
```
# 每个玩家最多创建多少个假人
# 默认: 1
player-limit: 1
```
config.yml中，修改了此项数值，为2，后来又尝试了四，修改后无论重启还是reload，都无法生效，玩家还是只能召唤一个假人
使用服务器核心为purpur1.20.1  2004

**Comment by tanyaofei** [comment]
这个问题我在下个大版本（支持 1.20.2）的时候修复吧
