### ISSUE TITLE
与MultiLogin冲突？

### ISSUE THREAD

**Issue by Harry-Pan** [tanyaofei/minecraft-fakeplayer#19]
服务器安装多种验证方式插件MultiLogin时插件无法正常工作，召唤假人时提示：

> 登陆失败，您需要通过MultiLogin的验证来进入服务器，如有疑问，请与服务器管理员取得联系。

![1](https://cos.harrypan.cn/usr/uploads/2023/11/1703033774.jpg)

**Comment by tanyaofei** [comment]
假人没有通过 `MultiLogin` 登陆而被它拦截登陆了，你可以考虑一下联系 `MultiLogin` 的作者，让他使用 IP 地址来判断这个是假人，假人会以 `127.x.x.x` 为 IP 进行登陆。
