### ISSUE TITLE
给出的构建文件缺失依赖，无法构建

### ISSUE THREAD

**Issue by Micalhl** [tanyaofei/minecraft-fakeplayer#2]
缺失的依赖：
- org.spigotmc:spigot:jar:remapped-mojang:1.20.1-R0.1-SNAPSHOT
- io.github.tanyaofei:plugintoolkit:jar:0.0.1

错误日志：
**org.spigotmc:spigot:jar:remapped-mojang:1.20.1-R0.1-SNAPSHOT** was not found in https://libraries.minecraft.net/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of minecraft has elapsed or updates are forced

Try to run Maven import with -U flag (force update snapshots)

**io.github.tanyaofei:plugintoolkit:jar:0.0.1** was not found in https://libraries.minecraft.net/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of minecraft has elapsed or updates are forced

Try to run Maven import with -U flag (force update snapshots)

**Comment by tanyaofei** [comment]
1. 你需要跟着这个[文档](https://www.spigotmc.org/wiki/buildtools/)在本地 maven 仓库里构建 `remmap mojang minecraft ` 
2. 这个工具箱我没开源，你可以解压 jar 包之后到源码目录里
