### ISSUE TITLE
希望能够支持1.19.2的版本

### ISSUE THREAD

**Issue by 2359395076** [tanyaofei/minecraft-fakeplayer#20]
您可以支持1.19.2的版本吗，有一个FakePlayers虽然显示支持1.19.2但是事实上在1.19.2上并不工作

**Comment by tanyaofei** [comment]
你好，感谢支持，估计是不会往后支持 `1.19.*`了，因为 `1.21` 生电将会有史诗级更新，后续都是跟随 mc 版本持续更新了

**Comment by tanyaofei** [comment]
没有后续的回复，关闭这个 issue
