### ISSUE TITLE
请问皮肤能不能优化一下 想从类似皮肤库或者其他方式加载假人的皮肤

### ISSUE THREAD

**Issue by ColdTearsYY** [tanyaofei/minecraft-fakeplayer#23]
如题，现在好像只能对服务器里在线的人获取皮肤（我不太会用owo）想改皮肤~

**Comment by tanyaofei** [comment]
可以对离线的玩家获取皮肤，只是命令行里没有名字补全提示，另外就是非 op 玩家 60 秒内只能获取一次非在线玩家皮肤
