### ISSUE TITLE
新功能请求/问题反馈：假人无法恢复饥饿值，且无法吃东西

### ISSUE THREAD

**Issue by mcbianxiao** [tanyaofei/minecraft-fakeplayer#25]
kick-on-dead设置为true时，在关闭无敌模式之后，当假人饥饿值掉到0的时候，通过杀死假人的方式无法使假人恢复饥饿值，且使用/fp use的命令也无法让假人进食。
在/fp use中，假人右键只能单点，没法长按，可以通过增加让假人长按右键的方式解决这个问题。
但经过实测，kick-on-dead设置为false的时候可以解决这个问题，但玩家使用/fp respawn的时候，会提示找不到匹配的假人

**Comment by tanyaofei** [comment]
设计上 /fp use( fp attack, fp mine) 的行为并不是点单，而是执行完一次完整动作，我在开发的时候用金苹果测试是正常的，请问你是让假人吃什么食物呢？

**Comment by mcbianxiao** [comment]
1.我这边测试，fp attack，fp mine的行为是没问题的。而fp use偶尔可以看见吃东西的粒子效果(所以推断可能是单点)，但更多的是没有任何反应。尝试让假人吃的食物是面包和金苹果。
2.服务器没有安装此类插件

插件版本是0.2.8

**Comment by mcbianxiao** [comment]
1. 我这边测试，fp attack，fp mine的行为是没问题的。而fp use偶尔可以看见吃东西的粒子效果(所以推断可能是单点)，但更多的是没有任何反应。尝试让假人吃的食物是面包和金苹果。在刚才测试的时候，发现喝药水的时候也是一样没有反应(喷溅型没问题)。其他有关右键的操作应该都没什么问题
2. 服务器没有安装此类插件

插件版本是0.2.8

**Comment by tanyaofei** [comment]
0.2.9 应该修复了这个bug，你可以更新留意一下

**Comment by mcbianxiao** [comment]
感谢 我会在之后集体更新插件的时候留意一下这个更改

**Comment by tanyaofei** [comment]
鉴于太久没有回复，此 issue 暂时关闭，如果后续还有问题欢迎重新打开
