### ISSUE TITLE
支持1.20.4

### ISSUE THREAD

**Issue by tjw123-tjw** [tanyaofei/minecraft-fakeplayer#28]
可以支持1.20.4吗，为什么不开发1.20.4的插件捏，可以捐助的

**Comment by tanyaofei** [comment]
是想着等1.21的

**Comment by tjw123-tjw** [comment]
可是在1.21出之前还是1.20.4捏
可以捐助的

**Comment by tanyaofei** [comment]
加 qq 864991375

**Comment by tanyaofei** [comment]
QQ 扫

![ee13731f99d82482c39d3c999e4a5c65](https://github.com/tanyaofei/minecraft-fakeplayer/assets/46375450/a15cd3e0-c3e9-4855-906e-0f8017f5b92e)

**Comment by Nymphxyz** [comment]
我尝试了一下自己构建，没有成功。作者release一下吧，万分感谢。

**Comment by tanyaofei** [comment]
已经发布了 https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.2.9
