### ISSUE TITLE
请发布1.20.4的jar包

### ISSUE THREAD

**Issue by YYYork** [tanyaofei/minecraft-fakeplayer#29]
看到您已经更新了1.20.4 我就想自己构建下，但是发现有些依赖是没有的，因此没办法构建，能否将更新后的插件发布在github上呢？

**Comment by Nymphxyz** [comment]
:sob: 作者看一眼吧。

**Comment by tanyaofei** [comment]
已经发布了 https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.2.9

**Comment by Nymphxyz** [comment]
好人一生平安。
