### ISSUE TITLE
无法召唤假人，游戏内提示"其他插件停止假人生成"

### ISSUE THREAD

**Issue by Esacpe-beep** [tanyaofei/minecraft-fakeplayer#32]
![ec7802bf8d4701e3d3eb4621420ef43c](https://github.com/tanyaofei/minecraft-fakeplayer/assets/64823961/88e900c6-d4c1-493f-8ee3-b10bd87867b9)
插件列表：
![image](https://github.com/tanyaofei/minecraft-fakeplayer/assets/64823961/823997e2-d716-4e33-8e6a-607a9d2fa83d)

**Comment by znc15** [comment]
解决了吗？

**Comment by Esacpe-beep** [comment]
没有

**Comment by tanyaofei** [comment]
新版本应该已经解决了此问题
