### ISSUE TITLE
能否新增支持1.20.6

### ISSUE THREAD

**Issue by lingszz** [tanyaofei/minecraft-fakeplayer#33]
能否新增支持1.20.6

**Comment by tanyaofei** [comment]
这两天快出1.21了吧 还需要吗

**Comment by lingszz** [comment]
> 这两天快出1.21了吧 还需要吗

那还是等1.21吧哈哈哈哈qaq

**Comment by tanyaofei** [comment]
我记得之前是说高考那几天出的哈哈

**Comment by tanyaofei** [comment]
0.3.1 已发布，支持 1.21。后续不会新增对 1.20.5, 1.20.6 的支持，兄弟们往前看把！

**Comment by Rebines** [comment]
但是purpur的1.21还处于测试版，不能保障稳定，1.20.6已经是稳定版了
