### ISSUE TITLE
fakeplayer与依赖于PacketEvent的插件有兼容性问题

### ISSUE THREAD

**Issue by NotKillerGod** [tanyaofei/minecraft-fakeplayer#35]
在使用依赖PacketEvent的插件 比如ForcePack Matrix等时会出现
[16:50:43 INFO]: Bot_AgOH_Frost_1 lost connection: PacketEvents 2.0 failed to inject
推测fakeplayer与依赖于PacketEvent可能有兼容性问题

**Comment by Esacpe-beep** [comment]
如何解决呢

**Comment by NotKillerGod** [comment]
> 如何解决呢

我现在个人的解决方法是直接跳过PacketEventAPI对假人检查的事件

**Comment by tanyaofei** [comment]
1.20.x 用这个 https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.2.10
1.21 用这个 https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.2
