### ISSUE TITLE
1.21支持

### ISSUE THREAD

**Issue by theLIKImk** [tanyaofei/minecraft-fakeplayer#37]
请问**1.21**的版本大概什么时候能适配

**Comment by tanyaofei** [comment]
这周末开始适配，由于 mojang 1.21 修改了玩家登陆相关的一些逻辑，可能需要时间，顺利的话周末就可以弄好

**Comment by tanyaofei** [comment]
已经发布了，请帮我验证怪物能否正常刷新，如果有条件可以帮我验证一些依赖 BungeeCord 通信的跨服插件是否正常，如跨服聊天

**Comment by theLIKImk** [comment]
刷怪正常，BungeeCord 目前怎么用倒是没检测

**Comment by tanyaofei** [comment]
> 刷怪正常，BungeeCord 目前怎么用倒是没检测

好嘞，感谢
