### ISSUE TITLE
关于服务器重启后需要重新设置假人.

### ISSUE THREAD

**Issue by Flock-YT** [tanyaofei/minecraft-fakeplayer#40]
请问有计划让插件保存假人数据在服务器重启后自动加入假人吗,不然每次重启后假人都要重放.

**Comment by tanyaofei** [comment]
要处理的地方很多
1. 记录假人自动生成名称的序列值
2. 记录假人坐标
3. 记录假人当前已经设置的动作
4. 如何处理可能是假人太多导致服务器炸掉重启后又召唤大量假人导致的循环崩服问题？

目前似乎没有太多人有这个需求，这个工作量有点大

**Comment by Flock-YT** [comment]
好吧,谢谢.
