### ISSUE TITLE
使用 /fp spawn 玩家名称 会报错 /fp spawn 则不会

### ISSUE THREAD

**Issue by hkkongou** [tanyaofei/minecraft-fakeplayer#47]
当使用 `/fp spawn 玩家名称` 时候，伺服器会报错，假人不会生成，但使用 /fp spawn 则不会。

purpur 1.20.1
fakeplayer-0.2.10

我打算用 mycommand 自动化重启后生成假人到指定位置，看来这样做不了

**Comment by tanyaofei** [comment]
有错误日志吗

**Comment by hkkongou** [comment]
https://paste.denizenscript.com/View/125062

**Comment by tanyaofei** [comment]
应该是 AntiPopup 导致的

**Comment by tanyaofei** [comment]
你可以试试升级到 0.3.6-rc1 之后的版本然后配置项里添加 `prevent-kicking: ALWAYS`
