### ISSUE TITLE
1.20.2 purpur端, OP权限无法再次召唤指定ID的假人

### ISSUE THREAD

**Issue by PPGC777** [tanyaofei/minecraft-fakeplayer#49]
1.20.2 purpur端
玩家A拥有OP权限, 第一次执行/fp spawn 玩家B_100 可以成功召唤假人
kill假人后, 第二次执行上述命令, 提示"名称已被使用"

**Comment by PPGC777** [comment]
![TY0S{XLR 6U{OET8JH{JEI](https://github.com/user-attachments/assets/ca42d10b-2cb1-478b-93f3-619919d61de7)
![5R4NR6QZS5WJ W93PK)9Q4N](https://github.com/user-attachments/assets/bbee6929-d3c2-46e1-97ae-0d7468c8032d)
fakeplayer 0.2.8版本
可能是其他插件(GroupManger)或者是fp版本太旧导致?

**Comment by tanyaofei** [comment]
这应该是这个 bug, 我没有在假人退出的时候做清理动作，现阶段你用 `/fp kill <假人名称>` 来清除假人吧

**Comment by tanyaofei** [comment]
你试试用 `/fp kill <假人>` 来删除看看

**Comment by PPGC777** [comment]
![KWSXYV`}T9@2)5QARY6LYXC](https://github.com/user-attachments/assets/da8398cd-b14a-49bc-8429-139c4529c296)
![SEPABU`UZN LA_JE274}NKL](https://github.com/user-attachments/assets/26ca25d3-9254-4378-8baf-5a493c458b46)
使用了fp kill来移除假人, 但是好像也不行

**Comment by tanyaofei** [comment]
这样的话你把服务端插件都发上来看看

**Comment by PPGC777** [comment]
![`NF5EOTPHFT4{MRS((7MGGT](https://github.com/user-attachments/assets/5a9d148b-1ba2-4d99-9df3-9bee17b69f8e)
[plugins.z01.zip](https://github.com/user-attachments/files/16361582/plugins.z01.zip)
[plugins.z02.zip](https://github.com/user-attachments/files/16361586/plugins.z02.zip)
[plugins.zip](https://github.com/user-attachments/files/16361587/plugins.zip)
插件和相关配置都在(除了CoreProtect插件用于记录方块的datebase.db), plugins.z01.zip和z02.zip需要先删除.zip后缀

**Comment by tanyaofei** [comment]
试一下最新的 0.3.8-rc 版本

**Comment by PPGC777** [comment]
> 试一下最新的 0.3.8-rc 版本

使用了`fakeplayer-0.3.9-b.1.jar`, 貌似是解决了, 不论使用`/fp kill`或者`/kill`, 均可以召唤指定name的假人
