### ISSUE TITLE
假人一生成就被踢出

### ISSUE THREAD

**Issue by cyt1260** [tanyaofei/minecraft-fakeplayer#53]
生成假人总会被系统踢出：

lost connection: PacketEvents 2.0 failed to inject

（没有开启服务器材质包，核心版本：paper-1.21-109）

**Comment by cyt1260** [comment]
![image](https://github.com/user-attachments/assets/7c5c183f-b22f-4035-b59e-a0f462789eed)

**Comment by tanyaofei** [comment]
大约一年前 PacketEvent 支持了假人的 `FakeChannel` 来跳过注入，你尝试一下升级 PackEvent 看看能否解决此问题，如果还不行，请通过 `/fp version` 查看版本号后截图发我以确定你已经是最新的 0.2.x 版本

**Comment by tanyaofei** [comment]
`0.3.5` 应该解决了这个问题
