### ISSUE TITLE
希望可以给予一个接口，用于译者对插件进行翻译工作

### ISSUE THREAD

**Issue by Ziyang-Bai** [tanyaofei/minecraft-fakeplayer#55]
一个接口，我指的是一种类似于Minecraft Mod的一个Lang文件，用于译者进行翻译，翻译完成后译者可以提交至开发者

**Comment by tanyaofei** [comment]
这其实是有的，只是我没有公开出来，你可以按照以下步骤进行翻译
1. 你可以在插件目录下新建一个文件夹 `message`，并复制 [message_zh.properties](https://github.com/tanyaofei/minecraft-fakeplayer/blob/master/fakeplayer-core/src/main/resources/message/message_zh.properties) 到该目录
2. 编写你的翻译文案，注意要使用 Unicode 字符而不是中文、繁体中文，你可以在网上找一些 Unicode 在线转译软件进行转译。
4. 将此文件修改为任意名称的语言文件如 `message_zh_Hant.properties`
5. 确保你的文件是以 `UTF-8` 编码，你可以借助 `Notepad++` 等软件确保，如果你是从我的文件里复制出来修改的，那一般是不用做特殊处理的。
6. 在 配置文件 `config.yml` 指定使用你的语言文件
```yaml
i18n:
  locale: zh_Hant
```


插件目录大概是这样的结构
```
plugins/fakeplayer
├── config.yml
├── data.db
├── message
│   └── message_zh_Hants.properties
├── serverid
└── used-uuids.txt
```
