### ISSUE TITLE
希望能给不同的玩家提供不同的语言

### ISSUE THREAD

**Issue by Ziyang-Bai** [tanyaofei/minecraft-fakeplayer#57]
希望能给不同的玩家提供不同的语言，使用类似于/fp:lang zh-cn
则该玩家使用中文简体
/fakeplayer:lang en-us
则该玩家使用美式英语
管理员可以使用
/fakeplayer:lang-default zh-cn
则服务器默认使用中文简体
使用/fakeplayer:lang ?
可列出所有支持的语言

如果有困难的话我可以提供帮助（PR）,但请指路。我自己也是一名Minecraft插件开发者和服务器管理员，不过这个目录结构确实令人有些困惑。

**Comment by tanyaofei** [comment]
这个插件使用了 Java ResourceBundle 的多国语言方案，被 purpur 的 API 所支持，因此我们其实可以通过获取玩家的游戏配置 `Player#locale()`来自动选用合适的语言文件。之前有考虑过做这个，但是发现好像都是国人在用于是我就没继续弄下去了。后面有时间可以搞一搞

**Comment by Ziyang-Bai** [comment]
不系这样的， 我有时候会做一些简单的Minecraft国际社区的工作，海外用户是有这个需求的，不过他们更多地使用Bukkit和Paper服务端。如果把这个很实用的工具放在SouceForge和CurseForge还有Modrinth上再做些YouTube的视频，我认为这个仓库的Star可以过1k

**Comment by tanyaofei** [comment]
哈哈哈那挺好，可以排上日程的

**Comment by Nymphxyz** [comment]
1K? 10k!
