### ISSUE TITLE
配置文件版本不匹配, 请备份并删除原有的配置文件并重新生成

### ISSUE THREAD

**Issue by XZH2024** [tanyaofei/minecraft-fakeplayer#58]
开启服务器后显示：[fakeplayer] 配置文件版本不匹配, 请备份并删除原有的配置文件并重新生成
删除配置文件并重载插件后仍然显示：[fakeplayer] 配置文件版本不匹配, 请备份并删除原有的配置文件并重新生成
删除配置文件并重启服务器后还是显示：[fakeplayer] 配置文件版本不匹配, 请备份并删除原有的配置文件并重新生成

fakeplayer0.3.5
CommandAPI-9.5.1
Leaf1.21
Java22

**Comment by GuYuan-V** [comment]
我也出现了同样的问题，哪怕整个文件夹删了也一样

**Comment by tanyaofei** [comment]
代码和配置文件的版本号没对上，下一个版本会修复这个问题

**Comment by XZH2024** [comment]
可以先提供下临时的解决方法吗？比如修改配置文件版本号之类的

**Comment by tanyaofei** [comment]
> 可以先提供下临时的解决方法吗？比如修改配置文件版本号之类的

将 `config.yml` 里的 version 改成 13
