### ISSUE TITLE
可以添加选项避免创建者下线后12000t自动踢出假人吗

### ISSUE THREAD

**Issue by Dreamail** [tanyaofei/minecraft-fakeplayer#60]
**Describe the feature you'd like / 描述你想要的新特性**
我想用假人挂刷怪塔但不想开着客户端，一开始以为是bug问题，但查了一下源码好像是预期行为
想问问能不能添加一个配置项，防止在创建者下线后踢出假人

**Comment by tanyaofei** [comment]
有这个配置项呀，follow-quiting 设置为 `false` 就可以了

**Comment by Dreamail** [comment]
> 有这个配置项呀，follow-quiting 设置为 `false` 就可以了

没有生效，依然还是在玩家下线后一段时间自动踢出假人

**Comment by Dreamail** [comment]
看来是配置reload有问题，重启服务器才好
