### ISSUE TITLE
假人无法生成

### ISSUE THREAD

**Issue by GuYuan-V** [tanyaofei/minecraft-fakeplayer#61]
前一天召唤假人还可以正常召唤就在今天服务器召唤假人出现图片的信息，一开始我以为是其他插件有冲突，当我删除所有插件只留下fakeplayer也没有任何用处，我测试了0.3.5和0.3.6rc2都一样，并且重新生成了配置文件，我并不确定是我的问题还是插件的问题因为前一天还在正常使用
![image](https://github.com/user-attachments/assets/17dd5258-134b-4040-90a8-5885a7cdf953)

 - Purpur2275  1.21
 - Java21
 - CommandAPI-9.5.1

**Comment by GuYuan-V** [comment]
召唤出来的假人没有实体，玩家列表有显示假人名字，传送过去什么也没有

**Comment by tanyaofei** [comment]
你可以将你的服务端压缩成压缩包之后发给我吗

**Comment by GuYuan-V** [comment]
[https://www.123pan.com/s/s79cVv-db0d3.html](url)

**Comment by GuYuan-V** [comment]
好像就只有我不行，其他玩家正常使用

**Comment by tanyaofei** [comment]
> 好像就只有我不行，其他玩家正常使用

那你考虑一下你是不是对 `GuYuan_V__1` 做了什么命令？你试试 指定名称生成看看比如 /fp spawn abc

**Comment by ximuya2** [comment]
> > 好像就只有我不行，其他玩家正常使用
> 
> 那你考虑一下你是不是对 做了什么命令？你试试 指定名称生成看看，比如 /fp spawn abc`GuYuan_V__1`

我也遇到了同样的问题

**Comment by ximuya2** [comment]
> > 好像就只有我不行，其他玩家正常使用
> 
> 那你考虑一下你是不是对 做了什么命令？你试试 指定名称生成看看，比如 /fp spawn abc`GuYuan_V__1`

![image](https://github.com/user-attachments/assets/dfacd94a-f0c2-4848-879d-2cdca851a0ed)

**Comment by ximuya2** [comment]
> > 好像就只有我不行，其他玩家正常使用
> 
> 那你考虑一下你是不是对 做了什么命令？你试试 指定名称生成看看，比如 /fp spawn abc`GuYuan_V__1`

我是群组服务器，只有在登录服务器才能生成假人

**Comment by tanyaofei** [comment]
> > > 好像就只有我不行，其他玩家正常使用
> > 
> > 
> > 那你考虑一下你是不是对 做了什么命令？你试试 指定名称生成看看，比如 /fp spawn abc`GuYuan_V__1`
> 
> 我是群组服务器，只有在登录服务器才能生成假人

使用 0.3.6-rc 版本，将 `prevent-kicking` 设置为 `ALWAYS` 不让其他插件踢掉假人

**Comment by ximuya2** [comment]
> > > > 好像就只有我不行，其他玩家正常使用
> > > 
> > > 
> > > 那你考虑一下你是不是对 做了什么命令？你试试 指定名称生成看看，比如 /fp spawn abc`GuYuan_V__1`
> > 
> > 
> > 我是群组服务器，只有在登录服务器才能生成假人
> 
> 使用 0.3.6-rc 版本，将 设置为 不让其他插件踢掉假人`prevent-kicking``ALWAYS`

![image](https://github.com/user-attachments/assets/b812ca40-9926-40d7-aca8-0bbebc9fdcd8)

**Comment by ximuya2** [comment]
![image](https://github.com/user-attachments/assets/b50cb0d4-5406-4adb-b0d2-e793f3761f5b)
感觉兼容问题有点难以解决

**Comment by tanyaofei** [comment]
@ximuya2 

1. 确认你使用 0.3.6-rc.1 以上版本
2. 确认 `prevent-kicking` 设置为 `ALWAYS`
3. 确认创建假人不会被踢掉，即使其他插件报错也没有关系

如果还不行，那这些插件没法兼容的，因为假人本身就没有通过各种登陆插件的登陆，特别是一些 bungeecord 方的登陆插件

**Comment by ximuya2** [comment]
> @ximuya2
> 
> 1. 确认你使用 0.3.6-rc.1 以上版本，我看你的控制台输出日志还是 0.3.5 版本的日志
> 2. 确认  设置为`prevent-kicking``ALWAYS`
> 3. 确认创建假人不会被踢掉，即使其他插件报错也没有关系
> 
> 如果还不行，那这些插件没法兼容的，因为假人本身就没有通过各种登陆插件的登陆，特别是一些 bungeecord 方的登陆插件

问题解决了，感谢

**Comment by GuYuan-V** [comment]
> > 好像就只有我不行，其他玩家正常使用
> 
> 那你考虑一下你是不是对 做了什么命令？你试试 指定名称生成看看，比如 /fp spawn abc`GuYuan_V__1`

使用其他名字是可以召唤的，默认的命名规则就不可使用了

**Comment by tanyaofei** [comment]
@GuYuan-V 那我觉得你这个很奇怪哦，你试一下关闭服务器后删除掉 `serverid` 和 `used-uuids.txt` 这两份文件，分别是存放 UUID 生成的种子以及使用过的 UUID

**Comment by tanyaofei** [comment]
> > @ximuya2
> > 
> > 1. 确认你使用 0.3.6-rc.1 以上版本，我看你的控制台输出日志还是 0.3.5 版本的日志
> > 2. 确认  设置为`` prevent-kicking``ALWAYS ``
> > 3. 确认创建假人不会被踢掉，即使其他插件报错也没有关系
> > 
> > 如果还不行，那这些插件没法兼容的，因为假人本身就没有通过各种登陆插件的登陆，特别是一些 bungeecord 方的登陆插件
> 
> 问题解决了，感谢

0.3.6 发布了，尽快升级一下，rc 版本连普通玩家也踢不出去😂，修复掉了

**Comment by GuYuan-V** [comment]
> 那我觉得你这个很奇怪哦，你试一下**关闭服务器后**删除掉 和 这两份文件，分别是存放 UUID 生成种子以及使用过的 UUID`serverid``used-uuids.txt`

解决了当我删除服务器所有玩家存档后这个问题就彻底解决了

**Comment by GuYuan-V** [comment]
在此询问一下，假人的攻击是否可以增加时间刻，攻击太快伤害过低，或者已经拥有这个功能我并没有发现

**Comment by tanyaofei** [comment]
> 在此询问一下，假人的攻击是否可以增加时间刻，攻击太快伤害过低，或者已经拥有这个功能我并没有发现如何使用

/fp attack interval <tick 间隔>
