### ISSUE TITLE
能否添加个根据权限判断玩家能创建最大假人数的功能

### ISSUE THREAD

**Issue by Chaostarts** [tanyaofei/minecraft-fakeplayer#64]
**Describe the feature you'd like / 描述你想要的新特性**
能否添加个根据权限判断玩家能创建最大假人数的功能 就像cmi 可以通过cmi.command.sethome.5 权限来指定玩家可以最大创建五个假人 能否增加这个功能

**Comment by tanyaofei** [comment]
与 https://github.com/tanyaofei/minecraft-fakeplayer/issues/9 重复

**Comment by Chaostarts** [comment]
已自行fork解决
