### ISSUE TITLE
class file major version 65

### ISSUE THREAD

**Issue by TenmaRen** [tanyaofei/minecraft-fakeplayer#66]
![b002537454104e2d7d20f189653214f5](https://github.com/user-attachments/assets/7eedc3b3-20b5-43a0-9f76-b9384a56b779)
服务端核心 pufferfish-paperclip-1.20.1-R0.1-SNAPSHOT-reobf  （paper衍生）
服务端java版本 jdk-21.0.4+7
使用的插件版本 fakeplayer-0.3.7
使用的前置版本 CommandAPI-9.5.1

球球大佬看看要如何解决这个难题

**Comment by tanyaofei** [comment]
确实是asm问题，原生purpur似乎可以通过升级同版本最后的build解决，因为这个依赖是purpur使用的，衍生核心的话可能要找找有没有别的办法

**Comment by TenmaRen** [comment]
已经尝试过1.20.1的paper，purpur依然遇到该问题，能否请求作者大大更新解决一下这个问题呢，非常抱歉打扰你的时间，感谢!~

**Comment by tanyaofei** [comment]
https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.8-rc.1 试试这个

**Comment by TenmaRen** [comment]
![B(FW1LTV4MLKRAU@OT@T920](https://github.com/user-attachments/assets/b81cbed7-fd81-4859-995c-a32bb91e4917)
创建假人时，会出现这类报错

**Comment by tanyaofei** [comment]
> ![B(FW1LTV4MLKRAU@OT@T920](https://private-user-images.githubusercontent.com/109287052/355660012-b81cbed7-fd81-4859-995c-a32bb91e4917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDMxNTUsIm5iZiI6MTcyMzAwMjg1NSwicGF0aCI6Ii8xMDkyODcwNTIvMzU1NjYwMDEyLWI4MWNiZWQ3LWZkODEtNDg1OS05OTVjLWEzMmJiOTFlNDkxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwMzU0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGIwOGQ1OWQzNTI5NjAyODc0YzkwZGE5MjEyZTVhNDZlYTRlYzljZGNiY2M0YjdmNzZiYWUyYTcxNDgwN2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YSeOo6e2efUJoyHKzns7-Wp7dvLneCBsedr8ul3DlEc) 创建假人时，会出现这类报错

看着不像是插件导致的问题，你再看看有没有别的日志，这里应该不是问题根源

**Comment by TenmaRen** [comment]
![5A)FG%H_0{R2E483L DC_{Y](https://github.com/user-attachments/assets/bcca8055-964f-4546-8c06-e80d218246a1)
只有创建才会出现，并没有其他报错了

**Comment by TenmaRen** [comment]
![9AFKX})F90M{F@MX$6 Q@EN](https://github.com/user-attachments/assets/7dc1c22d-9d43-40bc-9ddb-3bfc9a70fa00)
新的报错补充，删除假人时会出现的错误

**Comment by tanyaofei** [comment]
我甚至怀疑你这个是 ProtocolLib 的问题

**Comment by TenmaRen** [comment]
我去尝试升级protocollib的版本

**Comment by TenmaRen** [comment]
升级到最新版本似乎也并不能解决这个问题

**Comment by tanyaofei** [comment]
可以提供一下你的核心的下载地址吗

**Comment by TenmaRen** [comment]
https://pufferfish.host/downloads

1.20.1

**Comment by tanyaofei** [comment]
只能找到 1.20.4 的

**Comment by TenmaRen** [comment]
要不我直接上传我的核心？

**Comment by tanyaofei** [comment]
我不太确定是不是这个问题，你试试这个版本是否还是有问题 
[fakeplayer-0.3.8-rc.3.jar.zip](https://github.com/user-attachments/files/16539613/fakeplayer-0.3.8-rc.3.jar.zip)

**Comment by TenmaRen** [comment]
并不会出现报错了，生成，移除都并无报错了，感谢作者的帮助！~
