### ISSUE TITLE
白名單問題與建議

### ISSUE THREAD

**Issue by HanX2017** [tanyaofei/minecraft-fakeplayer#69]
由於我在伺服器中加入了白名單插件，白名單插件會直接把召喚的假人給擋了，所以我試著在preparing-commands加入指令讓創建假人時讓控制台給予假人白名單(指令中使用%p來取代玩家名)，但似乎因為判斷假人無法生成，插件直接就沒執行這指令了
建議增加功能讓大家可以在假人正要加入(還沒加入)時執行指令，實現加入前可以自動透過控制台把假人加入白名單

另外我有測試過讓假人在退出時刪除自己的白名單(放在destroy-commands)，這個功能是可以的

**Comment by tanyaofei** [comment]
https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.8-rc.1 试试这个 beta 版本，原来的 `preparing-commands` 不要了，改成 `pre-spawn-commands` 和 `post-spawn-commands`，你的白名单应该是放在 `pre-spawn-commands`
