### ISSUE TITLE
fakeplayer reload 后配置文件直接还原成最初，已检查无任何错误

### ISSUE THREAD

**Issue by TenmaRen** [tanyaofei/minecraft-fakeplayer#70]
reload时无任何报错，使用版本1.20.1 插件版本0.38

**Comment by tanyaofei** [comment]
fakeplayer 只会生成一份**模版**配置文件 `config.tmpl.yml`，需要你将这份文件重命名为 `config.yml` 来作为配置文件，这种方案在升级的时候，可以提前知道新的配置文件的新内容

**Comment by TenmaRen** [comment]
好的感谢！~
