### ISSUE TITLE
找不到依赖 io.github.hello09x:devtools

### ISSUE THREAD

**Issue by Chaostarts** [tanyaofei/minecraft-fakeplayer#71]
我想给服务器用的假人添加一点自定义功能，想着自己改点代码，但是无法下载到这些依赖
        <dependency>
            <groupId>io.github.hello09x</groupId>
            <artifactId>devtools-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.hello09x</groupId>
            <artifactId>devtools-command</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.hello09x</groupId>
            <artifactId>devtools-database</artifactId>
        </dependency>

**Comment by tanyaofei** [comment]
你好，这个我会在明天开放另外一个代码仓库来放这些代码

**Comment by frangametv** [comment]
Wow, i have the same problem. Wow, 8 minutes ago.
I have a Mohist server and the getMinecraftVersion() function doesn't work, and the plugin fails to load.
I decided to just replace the function with the string "1.20.1" and compile my own version, but i can't right now.

**Comment by tanyaofei** [comment]
@Chaostarts @frangametv 

现在可以用 [0.3.8](https://github.com/tanyaofei/minecraft-fakeplayer/tree/0.3.8) 分支来构建, `devtools` 已经上传到 jitpack 仓库
Now you could use [0.3.8](https://github.com/tanyaofei/minecraft-fakeplayer/tree/0.3.8), `devtools` is available from jitpack
