### ISSUE TITLE
您可以支持使用Spigot伺服器核心嗎

### ISSUE THREAD

**Issue by HanX2017** [tanyaofei/minecraft-fakeplayer#72]
paper/purpur 這類核心對minecraft原生功能修改太多，而這對於生電服很不利，希望可以支持spigot核心，來獲得更高的兼容性

**Comment by tanyaofei** [comment]
主要是 spigot 没有支持 kyroki 的文本 API，支持 spigot 的会让多语言支持非常麻烦。

在 purpur 这些支持了 `kyroki` 的核心里，我只需要提供一个文本 key，翻译的逻辑是由 purpur 在发送给玩家的时候去决定使用哪一份语言文本。

但是如果是 spigot，我在每一个发送消息给玩家的地方都要手动获取一次玩家的语言信息，自行翻译后再以文本的形式发送给玩家。
