### ISSUE TITLE
重启服务器重新创建，使用真实的皮肤 / Auto spawn after restarted, use skin of the real player

### ISSUE THREAD

**Issue by nate981120** [tanyaofei/minecraft-fakeplayer#73]
當伺服器重啟時 被踢出的假人會自動重新加入
這樣不用每次都重新生成

還有

能不能生成假人時 如果該假人的ID是實際存在的 直接套用該ID的skin

**Comment by tanyaofei** [comment]
你好，感谢反馈～

> 當伺服器重啟時 被踢出的假人會自動重新加入
关于这点可能需要更多的时间才能出这个功能，因为我想要的不仅仅只是加入游戏，还应当包括记录已经被设定好的行为

>能不能生成假人時 如果該假人的ID是實際存在的 直接套用該ID的skin
关于这点的话目前 `0.3.8-rc.3` 已经支持了皮肤记录，玩家通过 `/fp skin` 命令修改后，下一次召唤还是这个皮肤，但是前提是召唤者还是他，这个是以 `召唤人 ID + 假人 ID` 来进行记录的

**Comment by nate981120** [comment]
能不能 我付你一些錢 你單獨幫我修改一個會自動套用皮膚的版本

**Comment by tanyaofei** [comment]
> 能不能 我付你一些錢 你單獨幫我修改一個會自動套用皮膚的版本 因為我這個功能不是給玩家用的

噢可以的，是使用paypal支付吗
