### ISSUE TITLE
关于假人与玩家的绑定

### ISSUE THREAD

**Issue by tjw123-tjw** [tanyaofei/minecraft-fakeplayer#76]
能否实现假人仅能被创建者操作？
如/fp kill bot1时，其他玩家不能kill，仅创建者可以
同时设立/fpadmin 以保证管理者可以无视权限
类似/res /resadmin
可以嘛 谢谢您

**Comment by tanyaofei** [comment]
本身就是这么设计的，只有创建者可以操作自己的假人，可能是因为你是 OP，所以你可以操作所有假人，你可以尝试把 op 下了，这样是不会提示其他玩家创建的假人的
