### ISSUE TITLE
BungeeCord中跟随下线失效

### ISSUE THREAD

**Issue by 1642579950** [tanyaofei/minecraft-fakeplayer#8]
使用BungeeCord跨服中跟随下线失效。玩家下线后假人不会跟随下线

**Comment by 1642579950** [comment]
BungeeCord 中，在不同子服务器中可以 同时存在相同ID的多个机器人

BungeeCord 中无法限制单个玩家最大可创建假人的数量

**Comment by 1642579950** [comment]
假人死亡后无法再次生成出来

**Comment by tanyaofei** [comment]
> 使用BungeeCord跨服中跟随下线失效。玩家下线后假人不会跟随下线

BungeeCord 支持下的话需要至少有一名真实玩家处于加载了 `fakeplayer` 插件的情况下才能正常获取到所有服务器下的玩家列表，因此如果该服务器没有任何真实玩家，不会触发任何`跟随下线`

**Comment by tanyaofei** [comment]
> 假人死亡后无法再次生成出来

本身是没做这个的，如果你希望假人不会死亡，你可以通过 `/fp config set invulnerable true` 来配置假人的无敌模式

**Comment by 1642579950** [comment]
我以上指出的都是 bug 测试环境为 paper1.20.1  BC子服中

1. 假人死亡后，无法再召唤出同名的假人。 召唤时会直接显示死亡
这是我测试时的视频 链接 [http://www.ahmy.cc/未命名项目.mov](url)
