### ISSUE TITLE
Plugin doesn't load / 简要的标题有利于检索

### ISSUE THREAD

**Issue by GabrielVidalJR** [tanyaofei/minecraft-fakeplayer#82]
**Plugin errors out/ 描述你的 bug 情况**
java.lang.NoClassDefFoundError: net/kyori/adventure/translation/Translator / 简单描述这是一个什么 bug

**Server information / 服务器信息**
 - Spigot 1.21/ 核心: [e.g. Purpur 1.20.1]
 - 21: [e.g. 21]
 - 0.3.9/ 版本 [e.g. 0.3.1]

**Additional context / 更多信息**
Add any other context about the problem here. Such as log and plugin list / 添加更多有帮助的信息，如插件列表、日志

**Comment by PPGC777** [comment]
Not support Spigot yet.

**Comment by tanyaofei** [comment]
Only paper or purpur

**Comment by CodeZhangBorui** [comment]
kyroki Adventure 也支持 Bukkit 核心（[Document](https://docs.advntr.dev/platform/bukkit.html)），只是需要单独使用一个平台适配器，如果可能也尝试支持 Spigot？
