### ISSUE TITLE
给了玩家权限 但是还是无法使用命令

### ISSUE THREAD

**Issue by Chaostarts** [tanyaofei/minecraft-fakeplayer#89]
**Describe the bug / 描述你的 bug 情况**
![image](https://github.com/user-attachments/assets/5a9492c0-ad78-4682-b0cc-4334730fe5b2)
![image](https://github.com/user-attachments/assets/5c2b8285-d9b1-4f86-8ed4-5e13a5c5d337)
我已经给了玩家fakeplayer.* 权限 但是还是无法使用 这些命令
导致无法让玩家管理卡服的假人
**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. ...
2. ...
3. ...
4. ...

**Server information / 服务器信息**
 - Software / 核心: [e.g. Purpur 1.20.1] Leaves1.21
 - Java: [e.g. 21]zulu21
 - Version / 版本 [e.g. 0.3.1]0.3.9

**Additional context / 更多信息**
Add any other context about the problem here. Such as log and plugin list / 添加更多有帮助的信息，如插件列表、日志

**Comment by tanyaofei** [comment]
killall 命令代码里写死了只有 OP 才可以执行

**Comment by Chaostarts** [comment]
单个也不行

**Comment by tanyaofei** [comment]
或者你可以导出一下权限树看看
