### ISSUE TITLE
希望新增拥有权限可以召唤不同数量的假人

### ISSUE THREAD

**Issue by 1642579950** [tanyaofei/minecraft-fakeplayer#9]
希望新增拥有不同权限可以召唤不同数量的假人
如：
拥有 fakeplayer.1  权限最多可以召唤1个假人
拥有 fakeplayer.5 权限最多可以召唤5个假人

题外:

这是一个非常棒的插件，对于红石服务器非常有利。 我在服务器中试用了改插件，得到了玩家的一致好评
但是该插件还有许多不足和问题，希望能尽快修复。我也可以提供资金来定制我需要的功能🔎

**Comment by tanyaofei** [comment]
你好！感谢使用！
根据 mojang minecraft 开设服务器条款的内容，他们更希望所有玩家得到一致的体验，我自己本身也是在玩一个公益服，我不太希望这个插件根据玩家的充值而做差异化从而影响体验～
