### ISSUE TITLE
mine命令无法持续挖掘，导致不能破坏方块的问题

### ISSUE THREAD

**Issue by GenesisAN** [tanyaofei/minecraft-fakeplayer#90]
假人使用mine挖掘命令后，只会短按挖掘，导致无法破坏方块，但能破坏草，和甘蔗这类只需要单击就能破坏的对象。

触发方式：
1. 召唤假人 /fp spawn
2. 让假人执行挖掘命令 /fp mine
3. 在假人面前摆上甘蔗，可正常破坏
4. 在假人面前摆上原石，发现只会重复短暂挖掘一会（原石上显示出小裂缝，但不会持续扩大）

服务器信息
 - MC服务器核心:  PAPER - 1.21.1
 - Java: openjdk version "21.0.4" 2024-07-16 LTS
 - Version / 版本 0.3.9

更多信息
 - CommandAPI-9.5.3
 - 除了依赖插件外，无其他任何插件，基于itzg/minecraft-server的docker创建的全新服务器

**Comment by GenesisAN** [comment]
个人不是很懂相关API的调用，但看了看源码，可能问题出在这里:
在这段代码中定义了挖矿动作，但这个调用的动作是ActionSetting.once()
https://github.com/tanyaofei/minecraft-fakeplayer/blob/b9927bc2adff9b4f49498a954f3289406c88d2ee/fakeplayer-core/src/main/java/io/github/hello09x/fakeplayer/core/command/CommandRegistry.java#L228-L233
来到ActionSetting.once这里，这个是设置总次数为1，间隔为1，不过我不太清楚API的调用，没搞懂所谓的持续应该是怎么样的数值设置。
https://github.com/tanyaofei/minecraft-fakeplayer/blob/b9927bc2adff9b4f49498a954f3289406c88d2ee/fakeplayer-api/src/main/java/io/github/hello09x/fakeplayer/api/spi/ActionSetting.java#L44-L58

**Comment by tanyaofei** [comment]
我感觉你这个是不是假人的权限有问题，没有挖掘方块的权限

**Comment by GenesisAN** [comment]
> 我感觉你这个是不是假人的权限有问题，没有挖掘方块的权限

Paper端没有安装任何插件的情况下,只有一个假人插件,和依赖的CommandAPI插件,这也需要配置权限吗?我ESSX和LuckPerms都没安装的情况下应该不需要管权限方面的内容吧?🤔

**Comment by tanyaofei** [comment]
我这边经验证后确实有问题，过段时间会发一个新的版本来修复这个问题

**Comment by tanyaofei** [comment]
[0.3.10](https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.10) 已修复
