### ISSUE TITLE
假人无击退

### ISSUE THREAD

**Issue by u12e1juioj** [tanyaofei/minecraft-fakeplayer#92]
**Describe the bug / 玩家无法近战击退假人**
A clear and concise description of what the bug is. / 玩家攻击假人时假人无法收到击退，但可用弓等其他物品造成击退

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. 生成一个假人
2. 对着假人点左键攻击
3. 观察现象记录结果
4. 报告问题

**Server information / 服务器信息**
 - Paper 1.21.1 -82
 - Java: 21
 - Version 0.3.9

**Additional context / 
Add any other context about the problem here. Such as log and plugin list /

**Comment by tanyaofei** [comment]
这个击退行为应该是客户端控制的，所以没有击退

**Comment by Ziyang-Bai** [comment]
详见#94

**Comment by tanyaofei** [comment]
[0.3.10](https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.10) 已修复
