### ISSUE TITLE
假人攻击无法对盔甲架生效

### ISSUE THREAD

**Issue by elaina258** [tanyaofei/minecraft-fakeplayer#96]
**Describe the feature you'd like / 描述你想要的新特性**
...

**Comment by tanyaofei** [comment]
我这边正常，你说的不生效是什么意思

**Comment by elaina258** [comment]
砍盔甲架没有效果，同时也不触发横扫

**Comment by elaina258** [comment]
看假人一直在砍但是盔甲架一直都没动，横扫也不触发

**Comment by elaina258** [comment]
感谢大佬回复，这边测试了是因为服务器有领地插件假人在领地内没有权限攻击盔甲架。不是插件的问题

**Comment by tanyaofei** [comment]
好的哈
