### ISSUE TITLE
fp ride vehicle会坐到漏斗矿车里

### ISSUE THREAD

**Issue by skongkonga** [tanyaofei/minecraft-fakeplayer#97]
**Describe the bug / 描述你的 bug 情况**
fp ride vehicle会坐到漏斗矿车里

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. 生成一个假人
2. 放置一个漏斗矿车
3. 输入fp ride vehicle，触发bug

**Server information / 服务器信息**
 - Software / 核心: Purpur 1.21.1
 - Java: 21
 - Version / 版本 0.3.9

**Additional context / 更多信息**
![image](https://github.com/user-attachments/assets/f19123b4-d2f3-4961-9aed-732ae4a9e3ca)

**Comment by tanyaofei** [comment]
这不是一个bug，矿车确实是一个交通工具

**Comment by tanyaofei** [comment]
下一个版本修复
